CREATE DATABASE db_tutor_dev;
CREATE USER tutor WITH ENCRYPTIED PASSWORD 'tutor';
GRANT ALL PRIVILEGES ON DATABASE db_tutor_dev TO tutor;

CREATE DATABASE db_tutor_test;
CREATE USER tutor WITH ENCRYPTIED PASSWORD 'tutor';
GRANT ALL PRIVILEGES ON DATABASE db_tutor_dev TO tutor;

CREATE DATABASE db_tutor_prod;
CREATE USER tutor WITH ENCRYPTIED PASSWORD 'tutor';
GRANT ALL PRIVILEGES ON DATABASE db_tutor_dev TO tutor;

